# Site settings
title: Mehmet AKSAHIN
description: Merhaba! Bu benim kisisel amacli kullandigim web sitemdir.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/StaticWebsite/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://mehmetaksahin.github.io/StaticWebsite/" # the base hostname & protocol for your site
paginate:	3 # The number of posts to show per page on your homepage

# Social
facebook: memox.wfalcon
twitter: memox_wfalcon
github:  mehmetaksahin

#Additional Pages
about: aboutss
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: samanyougarg #github username
repo: hanuman #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://samanyougarg.com/
source_url:  https://github.com/samanyougarg/hanuman #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
